config/routes.rb
Rails.application.routes.draw do
  
  resources :casa_alugars
  root 'menu#_01index'

  get '/_buy', to:'menu#_buy'

  get '/_buy/casa', to:'menu#_apertou'

  get '/_help', to:'menu#_help'

  get '/_criar_buy', to:'casas#index'

  get '/new_buy', to:'casas#new'

  get '/new_hent', to:'casa_alugars#new'

  get '/_hent', to:'aluguel#index'

  get '/_criar', to:'menu#_intermedio'

  

  resources :casas



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casa.rb
class Casa < ApplicationRecord
end

app/models/casa_alugar.rb
class CasaAlugar < ApplicationRecord
end

app/controllers/aluguel_controller.rb
class AluguelController < ApplicationController
    def index

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/casa_alugars_controller.rb
class CasaAlugarsController < ApplicationController
  before_action :set_casa_alugar, only: %i[ show edit update destroy ]

  # GET /casa_alugars or /casa_alugars.json
  def index
    @casa_alugars = CasaAlugar.all
  end

  # GET /casa_alugars/1 or /casa_alugars/1.json
  def show
  end

  # GET /casa_alugars/new
  def new
    @casa_alugar = CasaAlugar.new
  end

  # GET /casa_alugars/1/edit
  def edit
  end

  # POST /casa_alugars or /casa_alugars.json
  def create
    
    if casa_alugar_params[:local].blank?
      flash[:error]= "Preencha o compo 'local'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:metragem].blank?
      flash[:error]= "Preencha o compo 'metragem'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:quartos].blank?
      flash[:error]= "Preencha o compo 'quartos'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:suites].blank?
      flash[:error]= "Preencha o compo 'suites'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:desconto].blank?
      flash[:error]= "Preencha o compo 'desconto'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:preco].blank?
      flash[:error]= "Preencha o compo 'preco'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:condominio].blank?
      flash[:error]= "Preencha o compo 'condominio'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:banheiros].blank?
      flash[:error]= "Preencha o compo 'banheiro'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:garagem].blank?
      flash[:error]= "Preencha o compo 'garagem'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:salas].blank?
      flash[:error]= "Preencha o compo 'salas'!"
      redirect_to "/new_hent"
      return
    end
    if casa_alugar_params[:cozinhas].blank?
      flash[:error]= "Preencha o compo 'cozinhas'!"
      redirect_to "/new_hent"
      return
    end


    @casa_alugar = CasaAlugar.new(casa_alugar_params)

    respond_to do |format|
      if @casa_alugar.save
        format.html { redirect_to @casa_alugar, notice: "Casa alugar was successfully created." }
        format.json { render :show, status: :created, location: @casa_alugar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @casa_alugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casa_alugars/1 or /casa_alugars/1.json
  def update
    respond_to do |format|
      if @casa_alugar.update(casa_alugar_params)
        format.html { redirect_to @casa_alugar, notice: "Casa alugar was successfully updated." }
        format.json { render :show, status: :ok, location: @casa_alugar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @casa_alugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casa_alugars/1 or /casa_alugars/1.json
  def destroy
    @casa_alugar.destroy
    respond_to do |format|
      format.html { redirect_to casa_alugars_url, notice: "Casa alugar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casa_alugar
      @casa_alugar = CasaAlugar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def casa_alugar_params
      params.require(:casa_alugar).permit(:local, :metragem, :banheiros, :suites, :cozinhas, :quartos, :salas, :garagem, :preco, :condominio, :desconto)
    end
end

app/controllers/casas_controller.rb
class CasasController < ApplicationController
  before_action :set_casa, only: %i[ show edit update destroy ]

  # GET /casas or /casas.json
  def index
    @casas = Casa.all
  end

  # GET /casas/1 or /casas/1.json
  def show
  end

  # GET /casas/new
  def new
    @casa = Casa.new
  end

  # GET /casas/1/edit
  def edit

  end

  # POST /casas or /casas.json
  def create

    if casa_params[:local].blank?
      flash[:error]= "Preencha o compo 'local'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:metragem].blank?
      flash[:error]= "Preencha o compo 'metragem'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:dormitorios].blank?
      flash[:error]= "Preencha o compo 'dormitorios'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:suites].blank?
      flash[:error]= "Preencha o compo 'suites'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:desconto_num].blank?
      flash[:error]= "Preencha o compo 'desconto_num'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:preco].blank?
      flash[:error]= "Preencha o compo 'preco'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:condominio].blank?
      flash[:error]= "Preencha o compo 'condominio'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:banheiro].blank?
      flash[:error]= "Preencha o compo 'banheiro'!"
      redirect_to "/new_buy"
      return
    end
    if casa_params[:garagem].blank?
      flash[:error]= "Preencha o compo 'garagem'!"
      redirect_to "/new_buy"
      return
    end

    @casa = Casa.new(casa_params)
    
    respond_to do |format|
      if @casa.save
        format.html { redirect_to @casa, notice: "Casa was successfully created." }
        format.json { render :show, status: :created, location: @casa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @casa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casas/1 or /casas/1.json
  def update
    respond_to do |format|
      if @casa.update(casa_params)
        format.html { redirect_to @casa, notice: "Casa was successfully updated." }
        format.json { render :show, status: :ok, location: @casa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @casa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casas/1 or /casas/1.json
  def destroy
    @casa.destroy
    respond_to do |format|
      format.html { redirect_to casas_url, notice: "Casa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casa
      @casa = Casa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def casa_params
      params.require(:casa).permit(:metragem, :local, :dormitorios, :suites, :banheiro, :garagem, :preco, :condominio, :desconto_num)
    end
    
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    
  end


end

app/helpers/aluguel_helper.rb
module AluguelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casa_alugars_helper.rb
module CasaAlugarsHelper
end

app/helpers/casas_helper.rb
module CasasHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aluguel/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comprar</title>
    <link rel="icon" href="../Assets/IconePag.png">
    <link rel="stylesheet" href="buy.css">
<style>

.titulo{
    color: rgb(236, 78, 78); 
    background-color: black; 
    text-align: center;
    width: 100%; 
    height: auto;
}
.corpo{
    border-radius:5px;
    background-color: brown;
    width: 100%;
    height: auto;
    text-align: center;
    border: 1px solid black;
}
td{
    border: 3px solid black;
    max-height:90px;
    max-width:50px;
    color:black;
    font-weight: bold;
}

img{
    margin-bottom:-10px;
    margin-left:-6px;
    max-width:104px;
    height:90px;
}

</style>

</head>

<!-- HTML -->

<body style="background-color: rgb(84, 88, 88);">
 
    <div class="titulo">
        <p style="font-size: 30px;">
            Bem vindo à aba aluga-se!
        </p>
    </div>

    <a href="/">
        <button style="background-color: black; border-radius: 10px; margin-top: 10px;margin-bottom:10px;">
            <p style="color: rgb(255, 255, 255);">
            Voltar para o menu
            </p>
        </button>
    </a>     




    <table class="corpo">

        <tr>
                    
            <td>
                Casa
            </td>
            <td >     
                Metragem
            </td>
            <td >                        
                Localização                   
            </td>
            <td>                             
                Quartos
            </td> 
            <td>
                Suites
            </td>
            <td>
                Banheiros
            </td>
            <td>
                Garagem
            </td>
            <td>
                Cozinha
            </td>
            <td>
                Salas
            </td>
            <td>
                Preço
            </td>
            <td>
                Preço<br>
                 do <br>
                condomínio
            </td>
            <td>
                Desconto
            </td>
        </tr>                   
           
        <% CasaAlugar.all.each do |casa_alugar| %>

                <tr>
                    <td class="image">
                        <a href="/_buy/casa">
                            <img src="assets/paisagem3.jpg">
                        </a>
                    </td>
                    <td >
                        <%= casa_alugar.metragem %>m²
                    </td>
                    <td >
                        <%= casa_alugar.local %>
                    </td>
                    <td>
                        <%= casa_alugar.quartos %>
                    </td>
                    <td>
                        <%= casa_alugar.suites %>
                    </td>
                    <td>
                        <%= casa_alugar.banheiros %>
                    </td>
                    <td>
                        <%= casa_alugar.garagem %>
                    </td>
                    <td>
                        <%= casa_alugar.cozinhas %>
                    </td>
                    <td>
                        <%= casa_alugar.salas%>
                    </td>
                    <td>
                        R$<%= casa_alugar.preco %>
                    </td>
                    <td>
                        R$<%= casa_alugar.condominio %>
                    </td>
                    <td>
                        <%= casa_alugar.desconto %>%
                    </td>
                </tr>

            <%end%>


    

</body>
</html>

app/views/casa_alugars/_form.html.erb
<%= form_with(model: casa_alugar) do |form| %>
  <% if casa_alugar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(casa_alugar.errors.count, "error") %> prohibited this casa_alugar from being saved:</h2>

      <ul>
        <% casa_alugar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local %>
  </div>

  <div class="field">
    <%= form.label :metragem %>
    <%= form.text_field :metragem %>
  </div>

  <div class="field">
    <%= form.label :banheiros %>
    <%= form.number_field :banheiros %>
  </div>

  <div class="field">
    <%= form.label :suites %>
    <%= form.number_field :suites %>
  </div>

  <div class="field">
    <%= form.label :cozinhas %>
    <%= form.number_field :cozinhas %>
  </div>

  <div class="field">
    <%= form.label :quartos %>
    <%= form.number_field :quartos %>
  </div>

  <div class="field">
    <%= form.label :salas %>
    <%= form.number_field :salas %>
  </div>

  <div class="field">
    <%= form.label :garagem %>
    <%= form.number_field :garagem %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :condominio %>
    <%= form.text_field :condominio %>
  </div>

  <div class="field">
    <%= form.label :desconto %>
    <%= form.text_field :desconto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/casa_alugars/edit.html.erb
<h1>Editing Casa Alugar</h1>

<%= render 'form', casa_alugar: @casa_alugar %>

<%= link_to 'Show', @casa_alugar %> |
<%= link_to 'Back', casa_alugars_path %>

app/views/casa_alugars/index.html.erb
<style>

body{
  background-color:#878c91;
}
.tabela{
  border-radius: 10px;
  color:white;
  background-color:black;
  
}
.cabeçalho{
    text-align: center;
    border-radius: 10px;
    border-width: auto;
    border-style: outset;
    border-color:red;
    background-color:black;
}
</style>

<p id="notice"><%= notice %></p>

<h1>Casas para Alugar</h1>

<div class="tabela">
  
  <table >
    <thead>
      <tr>
        <th class="cabeçalho">Local</th>
        <th class="cabeçalho">Metragem</th>
        <th class="cabeçalho">Banheiros</th>
        <th class="cabeçalho">Suites</th>
        <th class="cabeçalho">Cozinhas</th>
        <th class="cabeçalho">Quartos</th>
        <th class="cabeçalho">Salas</th>
        <th class="cabeçalho">Garagem</th>
        <th class="cabeçalho">Preco</th>
        <th class="cabeçalho">Condominio</th>
        <th class="cabeçalho">Desconto</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @casa_alugars.each do |casa_alugar| %>
        <tr>
          <td><%= casa_alugar.local %></td>
          <td><%= casa_alugar.metragem %></td>
          <td><%= casa_alugar.banheiros %></td>
          <td><%= casa_alugar.suites %></td>
          <td><%= casa_alugar.cozinhas %></td>
          <td><%= casa_alugar.quartos %></td>
          <td><%= casa_alugar.salas %></td>
          <td><%= casa_alugar.garagem %></td>
          <td><%= casa_alugar.preco %></td>
          <td><%= casa_alugar.condominio %></td>
          <td><%= casa_alugar.desconto %></td>
          <td><%= link_to 'Show', casa_alugar %></td>
          <td><%= link_to 'Edit', edit_casa_alugar_path(casa_alugar) %></td>
          <td><%= link_to 'Destroy', casa_alugar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Casa Alugar', new_casa_alugar_path %>

app/views/casa_alugars/new.html.erb
<html>

<style>

body{
    background-color:#e85656;
}
h1{
    
}

</style>

<body>

<h1>Nova Casa para Alugar</h1>

<%= render 'form', casa_alugar: @casa_alugar %>

<%= link_to 'Back', casa_alugars_path %>


</body>
</html>

app/views/casa_alugars/show.html.erb
<style>

  body{
    background-color:#6482b3;
  }

</style>


<body>
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Local:</strong>
    <%= @casa_alugar.local %>
  </p>
  
  <p>
    <strong>Metragem:</strong>
    <%= @casa_alugar.metragem %>
  </p>
  
  <p>
    <strong>Banheiros:</strong>
    <%= @casa_alugar.banheiros %>
  </p>
  
  <p>
    <strong>Suites:</strong>
    <%= @casa_alugar.suites %>
  </p>
  
  <p>
    <strong>Cozinhas:</strong>
    <%= @casa_alugar.cozinhas %>
  </p>
  
  <p>
    <strong>Quartos:</strong>
    <%= @casa_alugar.quartos %>
  </p>
  
  <p>
    <strong>Salas:</strong>
    <%= @casa_alugar.salas %>
  </p>
  
  <p>
    <strong>Garagem:</strong>
    <%= @casa_alugar.garagem %>
  </p>
  
  <p>
    <strong>Preco:</strong>
    <%= @casa_alugar.preco %>
  </p>
  
  <p>
    <strong>Condominio:</strong>
    <%= @casa_alugar.condominio %>
  </p>
  
  <p>
    <strong>Desconto:</strong>
    <%= @casa_alugar.desconto %>
  </p>
  
  <%= link_to 'Edit', edit_casa_alugar_path(@casa_alugar) %> |
  <%= link_to 'Back', casa_alugars_path %>
</body>

app/views/casas/_form.html.erb
<%= form_with(model: casa, :html => {onsubmit:"return validacao()"}) do |form| %>
    <% if casa.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(casa.errors.count, "error") %> prohibited this casa from being saved:</h2>

        <ul>
          <% casa.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :metragem %>
      <%= form.number_field :metragem %>
    </div>

    <div class="field">
      <%= form.label :local %>
      <%= form.text_field :local %>
    </div>

    <div class="field">
      <%= form.label :dormitorios %>
      <%= form.number_field :dormitorios %>
    </div>

    <div class="field">
      <%= form.label :suites %>
      <%= form.number_field :suites %>
    </div>

    <div class="field">
      <%= form.label :banheiro %>
      <%= form.number_field :banheiro %>
    </div>

    <div class="field">
      <%= form.label :garagem %>
      <%= form.number_field :garagem %>
    </div>

    <div class="field">
      <%= form.label :preco %>
      <%= form.text_field :preco %>
    </div>

    <div class="field">
      <%= form.label :condominio %>
      <%= form.text_field :condominio %>
    </div>

    <div class="field">
      <%= form.label :desconto_num%>
      <%= form.text_field :desconto_num %>
    </div>

    <div class="actions">
      <%= form.submit %>
    
    </div>

<% end %>

app/views/casas/edit.html.erb
<h1>Editing Casa</h1>

<%= render 'form', casa: @casa %>

<%= link_to 'Show', @casa %> |
<%= link_to 'Back', casas_path %>

app/views/casas/index.html.erb
</html>
<style>

body{
  background-color:#878c91;
}
.tabela{
  border-radius: 10px;
  color:white;
  background-color:black;
  
}
.cabeçalho{
    text-align: center;
    border-radius: 10px;
    border-width: auto;
    border-style: outset;
    border-color:red;
    background-color:black;
}
</style>

<body>
<div class="body">

<p id="notice"><%= notice %></p>

<h1>Casas para Comprar</h1>

<div class="tabela">
<table>
  <thead>
    <tr>
      <th class="cabeçalho">Metragem</th>
      <th class="cabeçalho">Local</th>
      <th class="cabeçalho">Dormitorios</th>
      <th class="cabeçalho">Suites</th>
      <th class="cabeçalho">Banheiro</th>
      <th class="cabeçalho">Garagem</th>
      <th class="cabeçalho">Preco</th>
      <th class="cabeçalho">Condominio</th>
      <th class="cabeçalho">Desconto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casas.each do |casa| %>
      <tr>
        <td > <%= casa.metragem %> </td>
        <td> <%= casa.local %> </td>
        <td> <%= casa.dormitorios %> </td>
        <td> <%= casa.suites %> </td>
        <td> <%= casa.banheiro %> </td>
        <td> <%= casa.garagem %> </td>
        <td> <%= casa.preco %> </td>
        <td> <%= casa.condominio %> </td>
        <td> <%= casa.desconto_num %> </td>
        <td> <%= link_to 'Show', casa %> </td>
        <td> <%= link_to 'Edit', edit_casa_path(casa) %> </td>
        <td> <%= link_to 'Destroy', casa, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>

<%= link_to 'New Casa', new_casa_path %>


</div>

</body>
</html>

app/views/casas/new.html.erb
<html>

<style>

body{
    background-color:#e85656;
}
h1{
    
}

</style>

<body>

<h1>Nova Casa para Comprar</h1>

<%= render 'form', casa: @casa %>

<%= link_to 'Back', casas_path %>

</body>
</html>

app/views/casas/show.html.erb
<style>

body{
  background-color:#344b70;
}
</style>

<body>
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Metragem:</strong>
    <%= @casa.metragem %>
  </p>
  
  <p>
    <strong>Local:</strong>
    <%= @casa.local %>
  </p>
  
  <p>
    <strong>Dormitorios:</strong>
    <%= @casa.dormitorios %>
  </p>
  
  <p>
    <strong>Suites:</strong>
    <%= @casa.suites %>
  </p>
  
  <p>
    <strong>Banheiro:</strong>
    <%= @casa.banheiro %>
  </p>
  
  <p>
    <strong>Garagem:</strong>
    <%= @casa.garagem %>
  </p>
  
  <p>
    <strong>Preco:</strong>
    <%= @casa.preco %>
  </p>
  
  <p>
    <strong>Condominio:</strong>
    <%= @casa.condominio %>
  </p>
  
  <p>
    <strong>Desconto:</strong>
    <%= @casa.desconto_num %>
  </p>
  
  
  <%= link_to 'Edit', edit_casa_path(@casa) %> |
  <%= link_to 'Back', casas_path %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imobiliária Sorge </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu/_01index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Imobiliária</title>
    <link rel="shortcut icon" href="../C_Assets/IconePag.png">
    <!-- Inicialização bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="01index.css">

    <style>

body{
    background-color: #000000;
    height: 100%;
    width: 100%;
}
.container{
    width: 100%;
    height: auto;
    background-color:red;
}
.titulo{
    background-color:#c40303; 
    border-radius: 10px;
    text-align: center;
    height: auto;

}
.header{
    background-color: #ff7575;
    height: auto;
    width: 99%;
    border-radius: 10px;
}
.button{
    background-color: #c40303;
    border-radius: 10px;
    margin-left: 10px;
    height: 45px;
    text-align: center;
    vertical-align: auto;
    font-size: 20px;
}
a:hover{
    background-color:transparent;
}
a:active{
    background-color:transparent;
}
button:active{
    background-color:transparent;
    color:red;
}
div.org{
    display: inline-flex;
}
.footer {
    position: absolute;
    bottom: 0;
    text-align: center;
    height: 90px;
    width:100%;
    background-color: #636363;
}
.carousel-item{
    height: 100%;  
    width: 100%;  
}
.preenchimento{
    text-align: center;
    background-color:#ff7575 ;
    width: 100%;
    height: 100px;
}
a.b_criar{
    color:#000000;
}
a.b_criar:active{
    color:#000000;
}
a.b_criar:hover{
    color:red;
    text-decoration:none;
}
a.b_criar:active{
    color:red;
}

    </style>

</head>
    
<body>
   
    <div class="header" style="margin-left: 5px; margin-top: 10px;">   
            
        <div class="titulo">
            
            <p style="color: transparent; text-shadow: 2px 0px 1px rgb(14, 14, 15); height: auto; padding-top:3px;">

                <strong style="font-size: 20px;">Imobiliária <strong style="font-size: 30px; font-family:cursive"> SORGE </strong> </strong>
                 
            </p>

        </div>
            
        <div class="org" style="text-align: center; margin-bottom: 5px; margin-top: -10px;">
            
            <a href="/_buy">
                    
                <button class="button" style="margin-left: 551.5px;">                       
                    Comprar
                </button>
                
            </a>
                
            <a href="/_hent">
                <button class="button">
                    Alugar
                </button>
            </a>

            <a href="_help.html" target="_blank">
                <button class="button">
                    Ajuda
                </button>
            </a>

        </div>
    </div>
    
</body>

        <!-- Carousel -->
    <div id="carouselSite" class="carousel slide" data-ride="carousel mx-auto d-block" style="margin-top: 10px ;background-color: hsl(0, 88%, 76%); height: 350px;" >

        <div class="carousel-inner">

            
                <div class="carousel-item active" style="margin-top: 50px;">
                    <img src="assets/paisagem1.jpg" class="img-fluid mx-auto d-block">
                </div>

                <div class="carousel-item" style="margin-top: 50px;">
                    <img src="assets/paisagem2.jpg" class="img-fluid mx-auto d-block">
                </div>
            
                <div class="carousel-item" style="margin-top: 50px;">
                    <img src="assets/paisagem3.jpg" class="img-fluid mx-auto d-block">
                </div>
            
            </div>
            
            <a class="carousel-control-prev" href="#carouselSite" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselSite" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>




        </div>
    </div>



    <div class="preenchimento" >

        <p style="padding-top:20px;">
            Este site foi desenvolvido com o intúito de ajudar as pessoas a encontrar suas respectivas casas dos sonhos.
        </p>

    </div>


    <div class="footer" style="margin-top: 5px;">

        <a class="b_criar" href="/_criar">
        <p>

            <br>
            Este site foi feito por Pedro da Costa Sorge &copy;<br>2021

        </p>
        </a>

    </div>

    <!-- Iniciação Jquerry Bootstrap-->
    
 
</body>
</html>